name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - h5py
  - scikit-learn
  - lalsuite
  - gwsurrogate
  - surfinBH
  - pip
  - pip:
    - NRSur7dq2
