name: example-environment
channels:
  - conda-forge
dependencies:
  - jupyterlab>=1.0
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - h5py
  - scikit-learn
  - lalsuite
  - ffmpeg
  - gwsurrogate
  - surfinBH
  - pip
  - pip:
    - NRSur7dq2
    - palettable
