name: example-environment
channels:
  - conda-forge
before_install:
  - sudo apt-get install -y libgsl-dev
  - travis_wait sudo add-apt-repository -y ppa:mc3man/trusty-media
  - travis_wait sudo apt-get install -y ffmpeg
dependencies:
  - numpy
  - scipy
  - matplotlib
  - h5py
  - scikit-learn
  - lalsuite
  - gwsurrogate
  - surfinBH
  - pip
  - pip:
    - NRSur7dq2
