name: sur_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - IPython
  - ipywidgets
  - h5py
  - ffmpeg
  - scikit-learn
  - lalsuite
  - gwsurrogate
  - surfinBH
  - pip
  - pip:
    - NRSur7dq2
    - palettable
    - forked-rompy
